export const columnDescriptions: { [key: string]: string } = {
    "ID": "This is a unique identifier of the accident record.",
    "Source": "Source of raw accident data.",
    "Severity": "Shows the severity of the accident, a number between 1 and 4, where 1 indicates the least impact on traffic and 4 indicates a significant impact.",
    "Start_Time": "Shows start time of the accident in local time zone.",
    "End_Time": "Shows end time of the accident in local time zone. End time refers to when the impact of the accident on traffic flow was dismissed.",
    "Start_Lat": "Shows latitude in GPS coordinate of the start point.",
    "Start_Lng": "Shows longitude in GPS coordinate of the start point.",
    "End_Lat": "Shows latitude in GPS coordinate of the end point.",
    "End_Lng": "Shows longitude in GPS coordinate of the end point.",
    "Distance(mi)": "The length of the road extent affected by the accident in miles.",
    "Description": "Shows a human provided description of the accident.",
    "Street": "Shows the street name in address field.",
    "City": "Shows the city in address field.",
    "County": "Shows the county in address field.",
    "State": "Shows the state in address field.",
    "Zipcode": "Shows the zipcode in address field.",
    "Country": "Shows the country in address field.",
    "Timezone": "Shows timezone based on the location of the accident (e.g., US/Eastern).",
    "Airport_Code": "Denotes an airport-based weather station which is the closest one to the location of the accident.",
    "Weather_Timestamp": "Shows the time-stamp of weather observation record (in local time).",
    "Temperature(F)": "Shows the temperature in Fahrenheit.",
    "Wind_Chill(F)": "Shows the wind chill in Fahrenheit.",
    "Humidity(%)": "Shows the humidity in percentage.",
    "Pressure(in)": "Shows the air pressure in inches.",
    "Visibility(mi)": "Shows visibility in miles.",
    "Wind_Direction": "Shows wind direction.",
    "Wind_Speed(mph)": "Shows wind speed in miles per hour.",
    "Precipitation(in)": "Shows precipitation amount in inches, if there is any.",
    "Weather_Condition": "Shows the weather condition (e.g., Rain, Snow, Fog).",
    "Amenity": "A POI annotation indicating presence of an amenity nearby.",
    "Bump": "A POI annotation indicating presence of a speed bump or hump nearby.",
    "Crossing": "A POI annotation indicating presence of a crossing nearby.",
    "Give_Way": "A POI annotation indicating presence of a give_way sign nearby.",
    "Junction": "A POI annotation indicating presence of a junction nearby.",
    "No_Exit": "A POI annotation indicating presence of a no_exit sign nearby.",
    "Railway": "A POI annotation indicating presence of a railway crossing nearby.",
    "Roundabout": "A POI annotation indicating presence of a roundabout nearby.",
    "Station": "A POI annotation indicating presence of a station nearby.",
    "Stop": "A POI annotation indicating presence of a stop sign nearby.",
    "Traffic_Calming": "A POI annotation indicating presence of a traffic_calming measure nearby.",
    "Traffic_Signal": "A POI annotation indicating presence of a traffic signal nearby.",
    "Turning_Loop": "A POI annotation indicating presence of a turning loop nearby.",
    "Sunrise_Sunset": "Indicates the period of day (Day or Night) based on sunrise/sunset.",
    "Civil_Twilight": "Indicates the period of day (Day or Night) based on civil twilight.",
    "Nautical_Twilight": "Indicates the period of day (Day or Night) based on nautical twilight.",
    "Astronomical_Twilight": "Indicates the period of day (Day or Night) based on astronomical twilight."
};